// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8DRwANgJYfLBU6irtIcqMqP7c218Bbls',
    appId: '1:658325554556:web:7be9c42c58b467261210f9',
    messagingSenderId: '658325554556',
    projectId: 'qr-scanner-app-ca1fb',
    authDomain: 'qr-scanner-app-ca1fb.firebaseapp.com',
    databaseURL: 'https://qr-scanner-app-ca1fb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'qr-scanner-app-ca1fb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjN2vfigz-vQLM2xiZGtnI4Wel7AuDjq8',
    appId: '1:658325554556:android:993ec13a4ab3701e1210f9',
    messagingSenderId: '658325554556',
    projectId: 'qr-scanner-app-ca1fb',
    databaseURL: 'https://qr-scanner-app-ca1fb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'qr-scanner-app-ca1fb.firebasestorage.app',
  );

}